services:
  database:
    image: postgres:latest
    container_name: price-loom-database
    environment:
      POSTGRES_DB: price-loom
      POSTGRES_USER: price-loom-user
      POSTGRES_PASSWORD: price-loom-password
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql

  rustfs:
    image: rustfs/rustfs:latest
    container_name: price-loom-storage
    volumes:
      - storage_rustfs_data:/data
      - storage_rustfs_logs:/app/logs
    environment:
      - RUSTFS_VOLUMES=/data
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfssecret
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  database_data:
  storage_rustfs_data:
  storage_rustfs_logs:
